// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjujnstpxgpuksaigtrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqdWpuc3RweGdwdWtzYWlndHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTA4NTUsImV4cCI6MjA2MDI4Njg1NX0.nXkMgvI0L7pNJCMgEKDBqIoRC_ewnpUaD38li3AyzMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);